### ISSUE TITLE
Add Tags to articles

### ISSUE THREAD

**Issue by egardner** [gettypubs/beyond-the-printed-page#1]
Add article tags to the site and make it possible for users to click into tag archive pages.

**Comment by egardner** [comment]
Tags are now showing up on archive pages, but don't currently do anything. Will attempt to create "tag pages" next.

**Comment by geealbers** [comment]
Nice! I just finished going through and consolidating the tags in all the posts into a more concise and consistent list. There are still a number of them that are far too broad to be meaningful, and I may take another crack at it at some point, but it's an improvement.

**Comment by egardner** [comment]
@geealbers here's what the current site-wide list of tags looks like, after your edit:
- content strategy 
- strategy 
- process/workflow 
- OSCI 
- devices 
- ebooks 
- platforms 
- awards/reviews/news 
- NMPS 
- digital humanities 
- free/open 
- Adobe 
- advanced features 
- UX/UI 
- design/creativity 
- digital media 
- backlist 
- collection/exhibition 
- reflowable 
- Apple 
- artist books 
- MCN
- rights/legal 
- distribution/discovery 
- DBW 
- professional development
- app 
- TOC
- tools 
- CAA 
- MW 
- web 
- fixed layout 
- stats 
- projects 
- BiB

I'd say the best approach is to keep the broader tags like `content strategy` and remove smaller random ones like `reflowable` and `apple`. Basically, treating the tags as categories of content. Something like:
- content strategy
- process/workflow
- ebooks
- ux/ui
- design
- distribution
- rights/legal
- conferences
- OSCI
- digital humanities
- open-source

**Comment by egardner** [comment]
@geealbers @sgrimes12 I've added a [Tags Page](http://gettypubs.github.io/beyond-the-printed-page/tags/) that will show every tag that's been defined in the site and all the posts belonging to it.

This is more to help you two as you're working with content, because a list like this is probably easier to navigate than a bunch of text files. This is not necessarily something we'll show to the end user (though we certainly could). Right now the page is not in navigation – just use the url here (/tags/).

**Comment by egardner** [comment]
Tags page has now been added to navigation: http://gettypubs.github.io/beyond-the-printed-page/topics/
As of now (ba266ab49ed6da55a845a6fc541a2148f6be0a70), post index pages and detail pages show a list of tag labels. When clicked, these go to the relevant anchor section of the Topics page.

For now, this is the best way to handle tag pages (Jekyll requires plugins to generate tag-specific pages, which are not supported on GitHub pages). We can build this out in the future if we deploy in a different environment.
