### ISSUE TITLE
Multiple authors in a single post?

### ISSUE THREAD

**Issue by geealbers** [gettypubs/beyond-the-printed-page#12]
It's an issue on only one post at this point, and so not critical, but does Jekyll allow for multiple authors for a single post?

http://gettypubs.github.io/beyond-the-printed-page/2014/03/17/workflow-go-go-minneapolis-institute-of-arts-verso-magazine/ 

(I commented out the second author name in the metadata for now)

**Comment by egardner** [comment]
There is no reason this should be a problem, but I'll have to set up the templates to look for multiple authors. If you uncomment the name I imagine both people will just show up in the title entry now (it might interfere with loading the blurb at the end though)

**Comment by geealbers** [comment]
Ok. I uncommented the second author and for now it seems the template picks up the second author listed and uses that as the post's author both at the top and for the author info at the bottom. I also added author info for both of them in the yml file so whenever you work on this (not a priority) you'll have some data there to test with.

**Comment by egardner** [comment]
This behavior is now supported as of 33f38d4.
When adding multiple authors to a post, just format the frontmatter as follows:

```
author: 
- Greg Albers
- Eric Gardner
```

For single-author posts, just continue to use the `author: Firstname Lastname` format on one line.
You can see this in action here: http://gettypubs.github.io/beyond-the-printed-page/2014/03/17/workflow-go-go-minneapolis-institute-of-arts-verso-magazine/

**Comment by geealbers** [comment]
Looks good. We just need a space between the author names at the top.

http://gettypubs.github.io/beyond-the-printed-page/2014/03/17/workflow-go-go-minneapolis-institute-of-arts-verso-magazine/

**Comment by egardner** [comment]
Good catch. I think I got that one:
http://gettypubs.github.io/beyond-the-printed-page/2014/03/17/workflow-go-go-minneapolis-institute-of-arts-verso-magazine/
