### ISSUE TITLE
Image and caption formatting

### ISSUE THREAD

**Issue by geealbers** [gettypubs/beyond-the-printed-page#13]
For all the WordPress imports, image markup looks something like this sample:

``` html
<p>[caption id="attachment_3459" align="alignright" width="300"]<a href="http://www.lateantiquesarcophagi.com/portfolio/finalhome.html"><img class="size-medium wp-image-3459" alt="Screen-Shot-2014-09-22-at-2.46.44-PM" src="{{site.baseurl}}/assets/img/Screen-Shot-2014-09-22-at-2.46.44-PM-300x197.jpg" width="300" height="197" /></a> Scholastic website showcasing Dionysian Sarcophagi. This site was created as a final project for the CLIO II class at GMU. Click on image to view the full website.[/caption]</p>
```

Using some GREP find and replace I think we could pretty easily get them all to something like this, and we could style the WP images and captions with CSS all at once. What do you think?

``` html
<p class="wp-image"><a href="http://www.lateantiquesarcophagi.com/portfolio/finalhome.html"><img alt="Screen-Shot-2014-09-22-at-2.46.44-PM" src="{{site.baseurl}}/assets/img/Screen-Shot-2014-09-22-at-2.46.44-PM-300x197.jpg" /></a> Scholastic website showcasing Dionysian Sarcophagi. This site was created as a final project for the CLIO II class at GMU. Click on image to view the full website.</p>
```

And I'm assuming that for new posts, especially written in Markdown, images will be handled differently but I haven't looked at that yet. What do they look like? And can they have styled captions?

**Comment by egardner** [comment]
Can you post your GREP query? I can do a dry run locally in Sublime and see what happens.
I don't think we need the `<a>` tags linking back to the old site. Just an `<img>` with a caption underneath (`<span class="caption">` would be an ideal element for this).

The standard way to insert an image in Markdown is:

``` markdown
![image-alt-text](path-to-your-img)
```

If other attributes are needed, you can always call the image in HTML (can be intermingled in your Markdown doc).

**Comment by geealbers** [comment]
Even though adding a span class makes sense, thinking ahead to writing new posts in Markdown it seems to mar the simplicity of the system a little if we have to always add that HTML snippet in to our Markdown and to instruct contributors to do the same. What do you think about just formatting captions as italic text right below the image? The HTML and Markdown versions are below and we'd just need to add `display: block` to the CSS for all post images to get the caption to drop a line.

```
HTML:
<p><img alt="Cracking Walnut" src="{{site.baseurl}}/assets/img/nutcrack.jpg" /> <em>Now that's nuts!</em></p>

Markdown:
![Cracking Walnut]({{site.baseurl}}/assets/img/nutcrack.jpg) _Caption: Now that's nuts!_
```

Though granted this wouldn't work super great for smaller images that don't fill much of the column width but that might have longer captions. I just don't see how to style images and captions for different situations without breaking the cleanliness and ease of the system...

Oh, and I haven't done/written the GREP query yet, I just figured it was probably possible based on the structure of the image mark up in the files.

**Comment by egardner** [comment]
I totally agree with this. For simple image captions, let's just use `_italics_` going forward.
I can look into a blanket find/replace change to implement this on all the old WP captions too.

**Comment by geealbers** [comment]
Super. Don't worry about doing a find/replace yet. I can tackle that all at once, I think, with some GREP. Just have to refresh my memory a bit...

**Comment by geealbers** [comment]
@egardner I finished reformatting the image markup. Could you add a `display:block rule` to images in posts so they'll knock the captions down a line as discussed? Thanks.

**Comment by egardner** [comment]
@geealbers I'll look for an elegant way to do this.
Do you want images forced to be full column width as well?

**Comment by geealbers** [comment]
I wouldn't force them. There are a lot of small legacy images in there that would look crazy that big. For new posts, I think people will realize they look better bigger and go that route on their own without us having to do it with style rules. And I could imagine sometimes that a little image is all that's called for anyhow.

**Comment by egardner** [comment]
You're right, there are too many low-res images on older posts for this to look good.
I've added the `display:block` property to all images inside of the main `<article>` elements now as of 0d83e5f
