### ISSUE TITLE
Sort behavior on publications prices

### ISSUE THREAD

**Issue by geealbers** [gettypubs/beyond-the-printed-page#14]
This doesn't seem to be working. The Price sort in the Survey/Publications section doesn't organize prices as expected: low to high or high to low. I'm betting it's probably just the $. Eric can you confirm this before Steph takes them all out of the csv file? And then let's just change the column heading to "Price ($)". Or can we add the $ back in programatically?

**Comment by egardner** [comment]
@sgrimes12  and I chatted about this today – this problem will go away once we clean up the data a bit.

I think the best approach is to use a value of `0` for everything that is free (not `0.00` or `free`). I'll change that to text that reads "Free". For other publications with a numerical value, we should just enter a numerical amount sans dollar-sign: `6.99` instead of `$6.99`, etc. I'll output this to read as a dollar amount, but it will be easier to parse if it's just numbers. Decimals are fine.

**Comment by egardner** [comment]
This is now working with the latest data. Sorts and searches are case-insensitive, can handle foreign currencies, and otherwise behave pretty naturally.

**Comment by geealbers** [comment]
The price sorts actually don't seem natural to me. I'd expect 0 to Highest Price, or Highest Price to 0, but what I'm seeing is:

British Pounds High to Low; Free; Dollars High to Low

or 

Dollars Low to High; Free; British Pounds Low to High

I think the Free ones really need to come before/after the lowest dollar amounts, not as their own category. If we have to do this by listing them as $0.00 rather than the word Free, I think that's fine.

And assuming we can't do some on the fly currency conversions I may prefer to have Steph do some for us manually in the CSV and then maybe add a note that Pounds have been converted. Let me know. The utility of the price sorting is to be able to compare different things that are being sold at the same price so I think we can give up some of the nicety of different currencies and such if need be.

Thanks.

**Comment by egardner** [comment]
Okay, I think I got this working:
http://gettypubs.github.io/beyond-the-printed-page/directory/

This includes the latest data as well (pounds converted to dollars, etc).
I was able to keep "0" in the HTML but replace it with the word "free" via CSS – so the sort function is still sorting numbers, they are just hidden from the user.

Last thing is to figure out if there's an easy way to add a count...

**Comment by egardner** [comment]
Added some icons to make things a little more clear (some links sort, other links take the user to external website, etc.)

**Comment by sgrimes12** [comment]
I really like the arrows, they definitely help the viewer understand that they can sort the information according to the category. I think the icons next to the links look a bit crowded and aren't necessary since the titles and institutions are already linked.

**Comment by geealbers** [comment]
+1 on the arrows. And on the offsite link icons, I think it's nice to indicate that those links do that, but agree that it's crowded with them now. How about putting them once in the column header after Title and Institution?

**Comment by egardner** [comment]
I'll try this. It's important to let people know before we take them somewhere outside of the site, but this might be sufficient.

**Comment by egardner** [comment]
Okay, I've continued to make improvements to the table functionality. The latest update now includes:
- Sticky headers that follow as you scroll
- correct sorting behavior
- icons that indicate sortability
- icons in the first two headers that indicate external links

The results count also has a live-update feature as the user types.
I think this is a pretty comprehensive feature set, but let me know if anything else should be added.

**Comment by geealbers** [comment]
Awesome work, thanks!

**Comment by sgrimes12** [comment]
Looks great!
