### ISSUE TITLE
acronyms vs full names for museums in survey 

### ISSUE THREAD

**Issue by sgrimes12** [gettypubs/beyond-the-printed-page#15]
I'm cleaning up the survey spreadsheet and am wondering about using museum acronyms vs. full names. (IE IMA instead of Indianapolis Museum of Art, LACMA instead of Los Angeles County Museum of Art). I think we should do one or the other for consistency but wanted input before I made changes.  I'm leaning towards acronyms to keep the layout clean/concise and theoretically our target audience will know what they stand for. Strong or indifferent thoughts on this?

**Comment by geealbers** [comment]
Did we decide we'd link Institution names to their websites and Title names to the specific books? If so, acronyms are fine. If not, I don't think something like SAM for Seattle Art Museum, or even IMA or AIC, have enough meaning to people and we should spell them out, or would have to add a Key of some sort.

**Comment by sgrimes12** [comment]
We are linking the institution names to their publications page. I'll do full names to keep it clear.
