### ISSUE TITLE
Corrections/Changes to Directory Info

### ISSUE THREAD

**Issue by geealbers** [gettypubs/beyond-the-printed-page#18]
Steph, can you make these few corrections/changes to the directory CSV?:
- There are a couple prices that have an extra space before them and aren't sorting correctly. Two Getty titles for $29.99 and $34.99.
- Please change MET to The Met
- For epub and mobi, let's combine them into one type "epub/mobi" and apply that to all of them. There are only a few outliers that are either in one or the other, and I'd rather fudge it so they all sort together. Also note that it can be all lower case, rather than ePub.
- For any publication that comes in multiple formats, let's create a new "Multiple" type and apply them like "Multiple: Website, epub/mobi, PDF". These will all then sort together, which seems more useful to me.
- And finally, can you convert all the British Pounds to dollars? Doesn't have to be exact or super accurate, but I think it would be better if they all sorted together with the Dollar ones, and a manual conversion sounds like the easiest way to do it.

Thanks!

**Comment by sgrimes12** [comment]
Just sent you the most up to date directory with these changes.
